---
########################################
# Read the instructions on the GitHub repository README.md on how to get these keys in order to allow the bot to farm Raids via Twitter.
########################################
"twitter":
  "apiKey": 
  "apiKeySecret": 
  "accessToken": 
  "accessTokenSecret": 

########################################
# Enable using Full Elixir or Soul Balms for refill.
########################################
"refill":
  "fullElixir": false
  "soulBalm": false

########################################
# Enable delay in seconds between runs to serve as a resting period.
# Note: If both enableDelayBetweenRuns and enableRandomizedDelayBetweenRuns is turned on, only enableDelayBetweenRuns will be used.
########################################
"delayBetweenRuns":
  "enableDelayBetweenRuns": false
  "delayInSeconds": 15 # Default is 15 seconds.
  "enableRandomizedDelayBetweenRuns": false
  "delayInSecondsLowerBound": 15 # Default is 15 seconds.
  "delayInSecondsUpperBound": 60 # Default is 60 seconds.

########################################
# Adjust the delay after performing the following actions as the bot is processing your combat script.
# The following timings are optimized at an average ping of around 120ms. You can find out your ping to the Granblue Fantasy servers by typing in your terminal on a computer:
# ping game.granbluefantasy.jp
# You do not need to worry about changing the idle time after attacking as the bot now waits until a new Turn begins before continuing.
########################################
"idleAfterAction":
  "idleAfterSkillInSeconds": 4 # Default is 4 seconds.
  "idleAfterSummonInSeconds": 7 # Default is 7 seconds.

########################################
# Settings for Dimensional Halo.
########################################
"dimensionalHalo":
  "enableDimensionalHalo": false
  "dimensionalHaloCombatScript":  # File name of the combat script text file in the same directory as this config.yaml file. If nothing, defaults to the settings used by Farming Mode.
  "dimensionalHaloSummonList": [] # Summon(s) to use separated by commas in order from highest to lowest priority. Please visit https://github.com/steve1316/granblue-automation-pyautogui/wiki/Selectable-Summons for selectable Summons. If nothing, defaults to the settings used by Farming Mode.
  "dimensionalHaloGroupNumber": 0 # If 0, defaults to the settings used by Farming Mode.
  "dimensionalHaloPartyNumber": 0 # If 0, defaults to the settings used by Farming Mode.

########################################
# Settings for Event Nightmares.
########################################
"event":
  "enableEventNightmare": false
  "eventNightmareCombatScript":  # File name of the combat script text file in the same directory as this config.yaml file. If nothing, defaults to the settings used by Farming Mode.
  "eventNightmareSummonList": [] # Summon(s) to use separated by commas in order from highest to lowest priority. Please visit https://github.com/steve1316/granblue-automation-pyautogui/wiki/Selectable-Summons for selectable Summons. If nothing, defaults to the settings used by Farming Mode.
  "eventNightmareGroupNumber": 0 # If 0, defaults to the settings used by Farming Mode.
  "eventNightmarePartyNumber": 0 # If 0, defaults to the settings used by Farming Mode.

########################################
# Settings for Rise of the Beasts Extreme+.
########################################
"rotb":
  "enableROTBExtremePlus": false
  "rotbExtremePlusCombatScript":  # File name of the combat script text file in the same directory as this config.yaml file. If nothing, defaults to the settings used by Farming Mode.
  "rotbExtremePlusSummonList": [] # Summon(s) to use separated by commas in order from highest to lowest priority. Please visit https://github.com/steve1316/granblue-automation-pyautogui/wiki/Selectable-Summons for selectable Summons. If nothing, defaults to the settings used by Farming Mode.
  "rotbExtremePlusGroupNumber": 0 # If 0, defaults to the settings used by Farming Mode.
  "rotbExtremePlusPartyNumber": 0 # If 0, defaults to the settings used by Farming Mode.

########################################
# Settings for Dread Barrage Unparalleled Foes.
########################################
"dreadBarrage":
  "enableUnparalleledFoe": false
  "enableUnparalleledFoeLevel95": false # You can only choose one. If you enable both, the bot will select Level 95. If none are selected, the bot will default to Level 95.
  "enableUnparalleledFoeLevel175": false
  "unparalleledFoeCombatScript":  # File name of the combat script text file in the same directory as this config.yaml file. If nothing, defaults to the settings used by Farming Mode.
  "unparalleledFoeSummonList": [] # Summon(s) to use separated by commas in order from highest to lowest priority. Please visit https://github.com/steve1316/granblue-automation-pyautogui/wiki/Selectable-Summons for selectable Summons. If nothing, defaults to the settings used by Farming Mode.
  "unparalleledFoeGroupNumber": 0 # If 0, defaults to the settings used by Farming Mode.
  "unparalleledFoePartyNumber": 0 # If 0, defaults to the settings used by Farming Mode.